use_frameworks!

platform :ios, '8.0'

target 'Componse_login_Example' do
  pod 'Componse_login', :path => '../'

  target 'Componse_login_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
